[package]
name = "strinclude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.10" }
indoc = "2.0.6"
itertools = "0.12.0"
regex = "1.10.2"
smol_str = "0.3.2"
